services:
  rev:
    build: .
    command: sh -c 'python /app/main.py --log-level $$LOG_LEVEL --email $$EMAIL --password $$PASSWORD $$EXTRA_ARGS'
    volumes:
      - .:/app
    environment:
      EXTRA_ARGS: ""
      LOG_LEVEL: DEBUG
      PYTHONUNBUFFERED: "1"
    env_file: "login.env"
